USE Round61;
GO
SELECT LEN('ARAFAT');
GO
SELECT LTRIM('ARAFAT');
GO
SELECT TRIM('ARAFAT');
GO
SELECT LEFT('ARAFAT',3);
GO
SELECT RIGHT('ARAFAT',4);
GO
SELECT SUBSTRING('ARAFAT',2,6);
GO
SELECT REPLACE('AAAA','ARAFAT','TUFAN');
GO
SELECT TRANSLATE('ARAFAT','RIMA','TINA');
GO
SELECT REVERSE('TAFARA');
GO
SELECT CHARINDEX('A','TINA');
GO
SELECT PATINDEX('RIMA','RIMA');
GO
SELECT CONCAT('ARAFAT',' ','TUFAN');
GO
--SELECT CONCAT_WS

SELECT LOWER('ARAFAT');
GO
SELECT UPPER('arafat');
GO
SELECT SPACE(2);
GO